name: Recover Keystore

on:
  workflow_dispatch:

jobs:
  recover:
    runs-on: ubuntu-latest
    steps:
      - name: Decode keystore from secret
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > upload-keystore.jks

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: recovered-keystore
          path: upload-keystore.jks
          retention-days: 1
